#!/bin/bash
cd /c/sheep
R1=ref/2b740dbd-0be0-42e5-92bb-1abc9aef6bc9.png
R2=ref/c0f6f4b1-4af2-410f-838a-9f2d25a3fa36.png
R3=ref/369c595b-d6f6-4f08-9cbb-a2729370ed58.png
R4=ref/fd55139a-01e5-4131-9ed2-79a9e02c5ecb.png
STYLE="16-bit SNES-era pixel art game background layer, same palette and rendering style as the reference game screenshots (Contra / Metal Slug style jungle stage), crisp chunky pixels, no text, no UI, no characters, no foreground ground."
g(){ node tools/gen.mjs "$@" > /dev/null 2>&1 && echo "done $2" || echo "FAIL $2"; }
g --out art/raw/world/sky.png --aspect 2048x1152 --bg opaque --quality high --n 2 --ref $R1 --ref $R4 --prompt "$STYLE Draw ONLY THE SKY: bright tropical daytime sky, saturated azure blue at the top fading to pale cyan-white near the bottom horizon, with a long bank of big fluffy white cumulus clouds with soft blue-grey pixel shading along the lower third, plus a few small wispy clouds higher up. Absolutely no mountains, no land, no trees, no birds - sky and clouds only, filling the whole frame." &
g --out art/raw/world/far.png --aspect 2048x1152 --bg transparent --quality high --n 2 --ref $R1 --ref $R2 --prompt "$STYLE Draw ONLY a wide panoramic range of very distant mountains on a fully transparent background (no sky). Two or three overlapping ridgelines of tall jagged tropical mountain peaks, pale hazy blue and blue-grey with atmospheric perspective (the farthest ridge lightest and bluest, the nearer ridge slightly darker blue-teal with hints of faint jungle texture), soft light from the upper left. The mountains span the full width edge to edge and their bases fill the bottom of the image solid. Nothing else." &
g --out art/raw/world/hills.png --aspect 2048x1152 --bg transparent --quality high --n 2 --ref $R1 --ref $R2 --prompt "$STYLE Draw ONLY a wide panoramic band of distant jungle-covered hills and forested mountain ridges on a fully transparent background (no sky). Blue-green teal colour affected by haze, dense rounded tree canopy texture covering the slopes, a few very distant tiny palm silhouettes on the ridge tops. Spans the full width edge to edge, the bottom of the image filled solid with forest. Nothing else." &
g --out art/raw/world/cliffs.png --aspect 2048x1152 --bg transparent --quality high --n 3 --ref $R1 --ref $R2 --ref $R3 --prompt "$STYLE Draw ONLY three separate distant jungle cliff massifs side by side on a fully transparent background, with clear empty space between them. Each is a tall rocky plateau cliff (grey-blue rock faces with green jungle overgrowth and hanging vines on top and ledges), and each has a tall white-blue waterfall pouring down its face into a misty white-foam plunge pool at the base. Mid-distance, slightly hazy blue-green. No sky, no ground strip." &
g --out art/raw/world/canopy.png --aspect 2048x1152 --bg transparent --quality high --n 2 --ref $R1 --ref $R2 --ref $R3 --prompt "$STYLE Draw ONLY a wide panoramic band of mid-ground tropical jungle on a fully transparent background (no sky): tall coconut palm trees with feathery fronds rising above a dense rounded jungle canopy of broadleaf trees and ferns, rich greens with slightly bluish haze, lit from the upper left. The canopy fills the bottom of the image solid from edge to edge; palms of varying heights poke up above it. Nothing else." &
g --out art/raw/world/base.png --aspect 2048x1152 --bg transparent --quality high --n 2 --ref $R4 --ref $R2 --ref $R3 --prompt "$STYLE Draw ONLY distant enemy military base structures seen in the background, on a fully transparent background, spread in a row with gaps: a tall steel lattice radar mast with a radar dish on top and a small red eagle banner, a concrete bunker with dark slit windows, a steel searchlight tower, a long chain-link fence with barbed wire on concrete posts, cylindrical fuel tanks, a grey concrete wall with yellow-black hazard stripes. Slightly hazy, mid-distance. No ground, no people." &
g --out art/raw/world/clouds.png --aspect 2048x1152 --bg transparent --quality high --n 1 --ref $R1 --ref $R4 --prompt "$STYLE Draw ONLY a set of 6 separate fluffy white cumulus clouds of different sizes on a fully transparent background, well spaced apart, with pixel-art blue-grey shading on their undersides like in the reference skies. Nothing else." &
wait
