#!/bin/bash
# generates every story panel (run from repo root)
T=ref/2f3330c3-2919-4954-83e8-50b26fc47907.png; H=ref/3c485156-1ab2-4472-a273-76e378d5eb05.png
STY="16-bit pixel art ACTION COMIC BOOK PANEL in exactly the style of the reference title screen: chunky crisp pixels, bold black comic ink outlines, halftone dot shading in the shadows, saturated colours, dramatic cinematic lighting. Full-bleed illustration, NO text, NO letters, NO speech balloons, NO captions, NO panel border, NO frame."
SHEEP="the commando sheep hero from the character sheet (fluffy cream wool body, grey face and ears, big round white eyes with black pupils, angry eyebrows, red headband with long trailing tails, golden bullet bandolier across the wool, black assault rifle)"
PRES="a fictional square-jawed silver-haired American President in a dark navy suit and red tie"
g(){ node tools/gen.mjs --out art/raw/story/$1.png --ref $T --ref $H --aspect $2 --quality high --bg opaque --n 2 --prompt "$STY $3" > art/raw/story/log_$1.txt 2>&1 & }
g p1 3:2  "Night. Inside the Oval Office: $PRES stands at the Resolute desk gripping a glowing RED telephone to his ear, alarmed. Tall windows behind him with rain and lightning, American flag, presidential seal on the carpet, warm lamp light versus blue storm light."
g p2 1:1  "Extreme close-up of $PRES shouting urgently into a red telephone handset, sweat on his brow, face lit red from below, speed lines behind him, dramatic comic close-up."
g p3 16:9 "A glowing military situation-room wall screen showing a satellite map of a dense jungle with a hidden enemy fortress and a secret laboratory dome, red eagle emblems and red target markers, soldiers with red banners bearing a black eagle, green radar sweep, dark room."
g p4 2:3  "Inside a dark jungle bunker hut with sandbags, a bare hanging lightbulb and ammo crates: $SHEEP sits up from a cot and snatches a ringing old red telephone off a crate, vibration lines around the phone, moody warm light."
g p5 16:9 "Close-up of $SHEEP tying the red headband tight around its woolly head with both hooves, the long headband tails flying, determined angry eyes, dark bunker background with rim light."
g p6 16:9 "Steely heroic close-up of $SHEEP, angry narrowed eyes, the golden bullet bandolier slung over the wool and the black assault rifle racked across its chest, dramatic low angle, orange rim light, dark background with speed lines."
g p7 16:9 "Dawn at a jungle military helipad: a big olive-drab military transport helicopter with spinning rotor blades, rotor wash flattening the palm trees, and $SHEEP running and leaping aboard through the open side door, orange sunrise sky."
g p8 16:9 "Wide shot at dawn: an olive-drab military transport helicopter flying low over an endless misty jungle canopy with waterfalls and mountains, orange and pink sunrise sky, sun rays, flock of birds, the helicopter silhouetted."
g p9 1:1  "$SHEEP leaping out of the open side door of a flying military helicopter, falling toward the dense jungle far below, rope trailing, headband tails whipping in the wind, dynamic diagonal composition, dawn light."
g e1 16:9 "A colossal explosion destroying a secret enemy laboratory fortress hidden in the jungle at night: giant orange mushroom fireball, debris, broken red eagle banners, shockwave rippling the palm trees."
g e2 16:9 "Sunrise: a military helicopter flies away from a burning jungle, and $SHEEP hangs from the rope ladder below it with one hoof, rifle raised in triumph, headband tails flying, smoke columns behind."
g e3 3:2  "On the White House lawn with American flags: $PRES pins a shining gold medal on the chest of $SHEEP, who stands at attention saluting proudly, confetti, warm golden light."
node tools/gen.mjs --out art/raw/story/chopper.png --ref $T --aspect 3:2 --quality high --bg transparent --n 2 --prompt "A single side-view sprite of a military transport helicopter (olive-drab Huey style) facing RIGHT, open side door, skids, tail rotor, main rotor blades drawn as a thin horizontal bar on top, 16-bit pixel art game sprite with a dark outline, isolated on a fully transparent background, no shadow, no text." > art/raw/story/log_chopper.txt 2>&1 &
wait
