cd /c/sheep
R=ref/levels/level3.png
S="16-bit SNES-era pixel art game asset in exactly the style and palette of the reference screenshot (Contra / Metal Slug style underground secret lab stage): cold teal and cyan glow against near-black steel, red accents, crisp chunky pixels, dark outlines. No text, no letters, no UI, no characters, no people."
g(){ node tools/gen.mjs "$@" > /dev/null 2>&1 && echo "done $2" || echo "FAIL $2"; }
g --out art/raw/stage3/backwall.png --aspect 2048x1152 --bg opaque --quality high --n 2 --ref $R --prompt "$S Draw ONLY a flat front-view far background WALL of the underground lab, filling the whole frame edge to edge: dark riveted steel bulkhead panels, vertical and horizontal pipe runs, hanging cable bundles, distant machinery cabinets, a few small cyan and teal indicator lights, darker toward the top. Low contrast, very dark (near-black blue-teal steel), no floor, no tanks, no windows, no doors." &
g --out art/raw/stage3/machines.png --aspect 2048x1152 --bg transparent --quality high --n 2 --ref $R --prompt "$S Draw ONLY a wide continuous row of lab machinery standing on a common flat baseline at the bottom, on a fully transparent background, spanning the full width: large vertical and elbow pipes with valves, generator cabinets, server racks with tiny green screens, conduit bundles, steel bulkhead pillars, cable trays. Dark steel with teal highlights. Nothing above them." &
g --out art/raw/stage3/tank.png --aspect 1024x1536 --bg transparent --quality high --n 2 --ref $R --prompt "$S Draw ONLY one single tall cylindrical specimen tank, front view, on a fully transparent background: thick dark steel cap on top with pipes and cables going up, a heavy machined steel base with small cyan lights, and a tall glass cylinder filled with bright glowing teal liquid with light streaks and a few bubbles. The tank is EMPTY: no creature inside." &
g --out art/raw/stage3/creature.png --aspect 1024x1024 --bg transparent --quality high --n 2 --ref $R --prompt "$S Draw ONLY one floating tentacled alien specimen creature (octopus-like head with many long curling tentacles hanging down), as a dark teal silhouette with subtle darker details, like the creatures seen inside the specimen tanks in the reference, on a fully transparent background." &
g --out art/raw/stage3/window.png --aspect 1536x1024 --bg transparent --quality high --n 2 --ref $R --prompt "$S Draw ONLY one huge wall-sized specimen observation window, front view, on a fully transparent background: a thick dark riveted steel frame, behind the glass glowing teal liquid with vertical light streaks, organic vein-like tubes, and a large dark tentacled creature in the middle. Nothing outside the frame." &
g --out art/raw/stage3/door.png --aspect 1024x1024 --bg transparent --quality high --n 2 --ref $R --prompt "$S Draw ONLY one sealed heavy steel blast door set in a thick riveted steel frame, front view, on a fully transparent background: grey steel door with a large black eagle emblem in the lower half and a blank plate in the upper half, yellow-black hazard stripe side panels, two round red warning lights on top of the frame, a cyan strip light above the door, a small green keypad panel beside it." &
g --out art/raw/stage3/props.png --aspect 1536x1024 --bg transparent --quality high --n 2 --ref $R --prompt "$S Draw ONLY a sprite sheet of separate lab props on a fully transparent background, well spaced, each standing on its own: a DNA computer terminal on a stand with a green screen showing a DNA double helix; a wall computer console with two green screens and small buttons; a stack of two olive-green military crates with black eagle emblems; a dark steel crate; a round red warning lamp on a bracket; a long cyan ceiling strip light fixture." &
g --out art/raw/stage3/floor.png --aspect 2048x1152 --bg opaque --quality high --n 2 --ref $R --prompt "$S Draw ONLY a side-view cross-section of an underground lab floor filling the frame edge to edge: across the top a thick riveted dark steel floor with a lit top edge, and below it a dark sub-floor full of horizontal and elbow pipes, valves, conduits, steel girders, a few yellow-black hazard striped pillars and small red lights, getting darker toward the bottom. Flat side view, no people." &
g --out art/raw/stage3/rock.png --aspect 1024x1536 --bg transparent --quality high --n 1 --ref $R --prompt "$S Draw ONLY one tall rough cave rock wall column, dark grey-brown rocky stone with cracks and chunky boulder texture, lit slightly from the right, on a fully transparent background, filling the full height." &
wait
