// GENERATED by art/raw/audio/synth.py - loop points (seconds) for the rendered music.
export const LOOPS = {
 "music-stage1": {
  "loopStart": 6.4,
  "loopEnd": 76.8
 },
 "music-title": {
  "loopStart": 4.137931,
  "loopEnd": 20.68966
 },
 "music-boss": {
  "loopStart": 0.0,
  "loopEnd": 22.325578
 }
};
